from collections.abc import AsyncGenerator
import json

from langchain_core.messages import HumanMessage

from server.dtos.chat import ChatRequest, ChatResponse
from server.graph import MessageState, graph


def extract_text(content) -> str:
    """Safely extract plain text from LangChain message content."""
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_parts = []
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                text_parts.append(block.get("text", ""))
            elif isinstance(block, str):
                text_parts.append(block)
        return "".join(text_parts)
    return str(content)


def invoke_chat(request: ChatRequest) -> ChatResponse:
    """Invoke the LangGraph workflow synchronously and return the final response."""
    user_message = HumanMessage(content=request.prompt)
    initial_state: MessageState = {
        "messages": [user_message],
        "llm_calls": 0,
    }
    final_state = graph.invoke(initial_state)
    last_message = final_state["messages"][-1]
    response_text = extract_text(last_message.content)
    return ChatResponse(
        response=response_text,
        tool_calls=[],
    )


async def stream_chat(request: ChatRequest) -> AsyncGenerator[dict, None]:
    """Stream token and tool execution events using LangGraph v2 event streaming."""
    user_message = HumanMessage(content=request.prompt)
    initial_state: MessageState = {
        "messages": [user_message],
        "llm_calls": 0,
    }

    async for event in graph.astream_events(initial_state, version="v2"):
        kind = event["event"]

        # 1. Text token generated by Gemini
        if kind == "on_chat_model_stream":
            chunk = event["data"].get("chunk")
            if chunk and hasattr(chunk, "content"):
                text = extract_text(chunk.content)
                if text:
                    yield {
                        "data": json.dumps({
                            "type": "token",
                            "content": text,
                        })
                    }

        # 2. Calculation tool began
        elif kind == "on_tool_start":
            yield {
                "data": json.dumps({
                    "type": "tool_start",
                    "tool": event.get("name", "unknown"),
                    "input": event["data"].get("input"),
                })
            }

        # 3. Calculation tool finished
        elif kind == "on_tool_end":
            yield {
                "data": json.dumps({
                    "type": "tool_end",
                    "tool": event.get("name", "unknown"),
                    "output": event["data"].get("output"),
                })
            }

    # 4. Stream completion signal
    yield {"data": json.dumps({"type": "done"})}
